flags: {}
allow-newer: true
packages:
  - '.'
  - location:
      git: https://github.com/expipiplus1/vulkan.git
      commit: bf651c43a190313d989a7051aa723d6642e7fe35
    extra-dep: true
extra-deps: []

resolver: lts-13.23
nix:
  enable: false
  pure: false
  packages: [vulkan-loader]
extra-lib-dirs:
- /run/opengl-driver/lib
